apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: panacea
spec:
  podSelector: {}
  policyTypes: [Ingress, Egress]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend
  namespace: panacea
spec:
  podSelector:
    matchLabels: {app: panacea-frontend}
  policyTypes: [Ingress, Egress]
  ingress:
    - ports:
        - {protocol: TCP, port: 3000}
  egress:
    - to:
        - podSelector:
            matchLabels: {app: panacea-backend}
      ports:
        - {protocol: TCP, port: 8000}
    - to:
        - namespaceSelector: {}
      ports:
        - {protocol: UDP, port: 53}
        - {protocol: TCP, port: 53}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend
  namespace: panacea
spec:
  podSelector:
    matchLabels: {app: panacea-backend}
  policyTypes: [Ingress, Egress]
  ingress:
    - ports:
        - {protocol: TCP, port: 8000}
  egress:
    - ports:
        - {protocol: TCP, port: 443}
        - {protocol: TCP, port: 9093}
        - {protocol: UDP, port: 53}
        - {protocol: TCP, port: 53}
